# Generated by Django 5.0.7 on 2024-08-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_post_content_img_post_promotion_alter_post_logo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company_num',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='promotion',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
