# Generated by Django 5.0.7 on 2024-07-30 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productionpost_category_productionpost_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salespost',
            name='user',
        ),
        migrations.RenameModel(
            old_name='RequestPost',
            new_name='Request',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=20)),
                ('category', models.CharField(choices=[('의상', '의상'), ('소품', '소품'), ('소모품', '소모품')], default='', max_length=10)),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='production_images/')),
                ('title', models.CharField(default='', max_length=50)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='logo_images/')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('company_num', models.CharField(default='', max_length=20)),
                ('company_img', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='production_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.post'),
        ),
        migrations.DeleteModel(
            name='ProductionPost',
        ),
        migrations.DeleteModel(
            name='RentalPost',
        ),
        migrations.DeleteModel(
            name='SalesPost',
        ),
    ]
