# Generated by Django 5.0.7 on 2024-08-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_post_company_num_alter_post_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
