# Generated by Django 5.0.7 on 2024-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_referenceimage_request_post_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='promotion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
