# Generated by Django 5.0.7 on 2024-07-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_production_post_request_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='request',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='reference_img',
            field=models.ImageField(blank=True, null=True, upload_to='reference_images/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.post'),
        ),
    ]
